### ISSUE TITLE
missing distinctive-gorge-3.dat

### ISSUE THREAD

**Issue by Keith-Hon** [ayaka14732/TransCan#3]

**Comment by Naozumi520** [comment]
Hi Keith!
Do you know the usage of this project? I'm currently having the same problem! If you know what the solution is please let me know 🙏

Thanks!

**Comment by Keith-Hon** [comment]
> Hi Keith!
> 
> Do you know the usage of this project? I'm currently having the same problem! If you know what the solution is please let me know 🙏
> 
> 
> 
> Thanks!

No, I don't. What are you trying to do?

**Comment by Naozumi520** [comment]
> No, I don't. What are you trying to do?

I hope to use this model for the most basic translation

**Comment by ayaka14732** [comment]
Sorry that I have been busy recently. I plan to update it soon

**Comment by ayaka14732** [comment]
I have fixed the errors and updated the README to include instructions for running the model.
